name: Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker://ghcr.io/artis3n/ansible_galaxy_collection:v2.4.2
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}
