name: Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker://ghcr.io/artis3n/ansible_galaxy_collection-testartifact:snapshot-8b1ae4bdf9eeddd7c0cc895e522115b0cf1fe15e
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}
