name: Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker://ghcr.io/artis3n/ansible_galaxy_collection-testartifact:snapshot-12b5dfe135c4edb16a33f66972bbe0bf932aed38
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}
